# -*- coding: utf-8 -*-
"""10_HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h7ejKkx7fPGRMtTynWMmeKlo2SibBX7J

Пингвины
"""

import pandas as pd
import seaborn as sns

penguins = sns.load_dataset("penguins")
penguins.head(10)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
sns.heatmap(penguins.corr())

# отношение длины плавника к массе тела по полу, соответственно особи муж пола крупнее и с длинными плавниками
sns.scatterplot(data=penguins, x="flipper_length_mm", y="body_mass_g", hue="sex")

# отношение длины клюва к ширине клюва по разновидностям, соответственно на графике видно, что у Адели короткие клювы и широкие, у Чинстрап длинные и широкие и у Дженту длинные и узкие
sns.scatterplot(data=penguins, x="bill_depth_mm", y="bill_length_mm", style="species")

# отношение массы тела к виду, на графике видно, что Чинстрап и Адели в одной весовой категории, но Чинстрап находятся только на острове Dream, когда как Адели на всех островах, а Дженту по массе больше, но находятся на острове Biscoe
sns.scatterplot(data=penguins, x="body_mass_g", y="species", size="island")

sns.histplot(data=penguins, x="body_mass_g")

sns.histplot(penguins, x="island", hue="species")

cols = ['bill_length_mm', 'bill_depth_mm']
g = sns.PairGrid(penguins[cols])
g.map(sns.scatterplot)