# -*- coding: utf-8 -*-
"""9_HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZMBpxzkDs8vd4Lmvgg5pMchGQKlpqbM4

1. Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)
"""

import pandas as pd

df = pd.read_csv('sample_data/california_housing_train.csv')

df[df['population'] < 500]['median_house_value'].mean()

""" 2. Узнать какая максимальная households в зоне минимального значения population"""

df[df['population'] < 800]['households'].max()